### PR TITLE
Update to 2.14.0

### PR DESCRIPTION
**Pull request by saecki**
I'm having some difficulties with `2.12.0` but tagged and tested:

- `2.11.5`
- `2.11.6`
- `2.11.7`
- `2.11.8`

Edit: 
Adding the `maven-publish` plugin and a release configuration fixed the problems I encountered for these versions:

- `2.12.0`
- `2.12.1`
- `2.12.2`
- `2.12.3`
- `2.13.0`
- `2.13.1`

As of `2.13.2` google added the `maven-publish` plugin and a configuration themselves. So I removed our plugin declaration and configuration again for these versions:

- `2.13.2`
- `2.13.3`

Edit:
Added new version:
- `2.14.0`

### CODE REVIEW

**Comment by saecki** [comment]
Hi there? 🙃

**Comment by PaulWoitaschek** [comment]
Sorry, really busy right now. Based on your changes I just released 2.14.0, thanks for your work!

**Comment by saecki** [comment]
No problem, thanks!

**Comment by PaulWoitaschek** [comment]
It's was kind of hard to track what you did in that 3500 commits PR 🙃

**Comment by saecki** [comment]
Yeah I can imagine. Would you mind also tagging the release `2.13.3`?

**Comment by Saecki** [comment]
The hash of the merge commit is `015106d10e4c88d58fca4c09ccf283087721fd06`.

**Comment by PaulWoitaschek** [comment]
For 2.13.3 you should be able to just point to your fork and let jitpack do it's magic.

**Pull request closed without merging**
