### PR TITLE
Merge recent ExoPlayer releases

### PR DESCRIPTION
**Pull request by hdasch**
Issue #2 invites pull requests for compatibility with recent exoplayer versions.  So, here goes.

This is attempt to update the extensions for exoplayer releases since r14.0.  There are ten merges in this changset based on the following release tags:
- r14.1
- r14.2
- r15.0
- r15.1
- r16.0
- r16.1
- r17.0
- r17.1
- r18.0
- r18.1

Each at least compiles.  The last merge has been tested and does improve FLAC playback.  Tracks that would not play without the extensions do play with head of tree with these changes.

The only significant merge issue arose in -r16.0 where the library added the modules:
- database
- datasource
- extractor

The changes to accommodate these new modules follows the pattern of previous changes: `testImplementation` lines for `robolectricVersion`, `testdata`, and `testutils` were removed from the module's `build.gradle` files.

Otherwise, the `git diff` output between the `rxx.y` tags and `xx.y` tages look quite similar.

### CODE REVIEW

**Comment by PaulWoitaschek** [comment]
Thanks! Merged :)

**Comment by hdasch** [comment]
Thank you.  I did not realize tags do not propagate through a pull request.  In order to allow jitpack.io to serve build artifacts, would you consider running?:
```
git tag 2.18.1 789a4f83169cff5c7a91655bb828fde2cfde671a
git tag 2.18.0 7a03e52bd81b8307b6b67045f8bb569e0e3beedc
git tag 2.17.1 5d9a079c47aea85cdaab84709aa81e71d558b249
git tag 2.17.0 b8919c3dec47ba8bcc25ff6f6b4350ef838d7e98
git tag 2.16.1 8479f68bda0364cce49f969ce9358082c1f34bde
git tag 2.16.0 7d1423d41ccbcf295096fae89e37aa9b71ef11d4
git tag 2.15.1 8ef308908bcd029112faa3080394d2bcf8af70cf
git tag 2.15.0 7c1ac07095b0129a7ba5b9cfdaf189688dd0e135
git tag 2.14.2 ea0a5f3a0d92369b15201e31fae6304496d67c04
git tag 2.14.1 05a587fdf0bb7e70e894da3595051f3aa114e316
git push --tags origin
```
I can point my project to my own repository.  But yours is better known.  Being able to pull builds based on your repository would be more useful.

Thanks again,
Hugh

**Comment by PaulWoitaschek** [comment]
In the meantime you can use commit shas

**Comment by hdasch** [comment]
Missed that in the documentation.  See it now.  Thanks for the hot tip.

**Pull request merged**
